# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/project_8.2/project_8.2.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/project_8.2/project_8.2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado_projects/project_8.2/project_8.2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/vivado_projects/rv32i-core/src/core/rv32i_defs.vh
read_mem D:/vivado_projects/rv32i-core/src/cpu_basys3/inst_mem_init.mem
read_verilog -library xil_defaultlib {
  D:/vivado_projects/rv32i-core/src/cpu_basys3/debounce.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_alu.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_alu_control.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_alu_opb_mux.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_branch_unit.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_control.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_cpu.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_imm_gen.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_instr_decoder.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_instr_mem.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_pc_reg.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_rd_data_mux.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_reg_file.v
  D:/vivado_projects/rv32i-core/src/cpu_basys3/seg_display.v
  D:/vivado_projects/rv32i-core/src/cpu_basys3/cpu_basys3.v
  D:/vivado_projects/rv32i-core/src/core/rv32i_data_mem.v
  D:/vivado_projects/project_8.2/project_8.2.srcs/sources_1/new/clock_divider.v
  D:/vivado_projects/rv32i-core/src/cpu_basys3/scan_clk.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/rv32i-core/src/cpu_basys3/basys3.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/rv32i-core/src/cpu_basys3/basys3.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top riscv_cpu_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_cpu_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_cpu_top_utilization_synth.rpt -pb riscv_cpu_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
