# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Vivado_project/cpu_tengf/cpu_tengf.cache/wt [current_project]
set_property parent.project_path D:/Vivado_project/cpu_tengf/cpu_tengf.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Vivado_project/cpu_tengf/cpu_tengf.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_defs.vh
read_mem {
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/cpu_basys3/inst_mem_init.mem
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/new/LUI_test.mem
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/new/AUIPC_test.mem
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/new/inst_mem_init+SWLW.mem
}
read_verilog -library xil_defaultlib {
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_alu.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_alu_control.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_alu_opb_mux.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_branch_unit.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_control.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_data_mem.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_imm_gen.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_instr_decoder.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_instr_mem.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_pc_reg.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_rd_data_mux.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_reg_file.v
  D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/sources_1/imports/src/core/rv32i_cpu.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/constrs_1/new/cpu_constr.xdc
set_property used_in_implementation false [get_files D:/Vivado_project/cpu_tengf/cpu_tengf.srcs/constrs_1/new/cpu_constr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top rv32i_cpu -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rv32i_cpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rv32i_cpu_utilization_synth.rpt -pb rv32i_cpu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
